/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as reviewAnchorSol from "./ReviewAnchor.sol";
export type { reviewAnchorSol };
export type { AttendanceProof } from "./AttendanceProof";
export type { TicketPass } from "./TicketPass";
