/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as reviewAnchorSol from "./ReviewAnchor.sol";
export type { reviewAnchorSol };
import type * as ticketPassSol from "./TicketPass.sol";
export type { ticketPassSol };
import type * as mocks from "./mocks";
export type { mocks };
export type { AttendanceProof } from "./AttendanceProof";
