/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AggregatorV3Interface } from "./AggregatorV3Interface";
export type { IAttendanceProof } from "./IAttendanceProof";
export type { TicketPass } from "./TicketPass";
