/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TicketPassInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "PLATFORM_FEE_BPS"
      | "REFUND_LOCK_BEFORE_START"
      | "acceptedStableTokens"
      | "approve"
      | "attendanceProofAddress"
      | "avaxUsdPriceFeed"
      | "balanceOf"
      | "buyTicket"
      | "buyTicketWithERC20"
      | "buyTicketWithNative"
      | "cancelEvent"
      | "configureTicketType"
      | "eventCanceled"
      | "eventEndAt"
      | "eventExists"
      | "eventNativeBalance"
      | "eventOrganizer"
      | "eventSettled"
      | "eventStartAt"
      | "eventTicketBalanceOf"
      | "eventTokenBalance"
      | "getApproved"
      | "getStableTokens"
      | "hasBought"
      | "hasValidTicket"
      | "isApprovedForAll"
      | "maxPriceAge"
      | "name"
      | "owner"
      | "ownerOf"
      | "platformTreasury"
      | "quoteNativePriceWei"
      | "refundCanceledTicket"
      | "refundCanceledTickets"
      | "refundCutoffAt"
      | "registerEvent(uint256,address)"
      | "registerEvent(uint256,address,uint64,uint64)"
      | "renounceOwnership"
      | "requestRefund"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "setAttendanceProofAddress"
      | "setAvaxUsdPriceFeed"
      | "setEventTimeRange"
      | "setMaxPriceAge"
      | "setPlatformTreasury"
      | "setStableToken"
      | "settleEvent"
      | "supportsInterface"
      | "symbol"
      | "ticketInfoOf"
      | "ticketTypes"
      | "tokenURI"
      | "transferFrom"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "ApprovalForAll"
      | "AttendanceProofUpdated"
      | "AvaxUsdPriceFeedUpdated"
      | "EventCanceled"
      | "EventRegistered"
      | "EventSettled"
      | "EventTimeRangeUpdated"
      | "EventTokenSettled"
      | "MaxPriceAgeUpdated"
      | "OwnershipTransferred"
      | "PlatformTreasuryUpdated"
      | "StableTokenUpdated"
      | "TicketMinted"
      | "TicketPaid"
      | "TicketRefunded"
      | "TicketTypeConfigured"
      | "Transfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REFUND_LOCK_BEFORE_START",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptedStableTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "attendanceProofAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "avaxUsdPriceFeed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "buyTicket",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyTicketWithERC20",
    values: [BigNumberish, BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyTicketWithNative",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelEvent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "configureTicketType",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "eventCanceled",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "eventEndAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "eventExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "eventNativeBalance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "eventOrganizer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "eventSettled",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "eventStartAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "eventTicketBalanceOf",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eventTokenBalance",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStableTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasBought",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasValidTicket",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxPriceAge",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "platformTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "quoteNativePriceWei",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "refundCanceledTicket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "refundCanceledTickets",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "refundCutoffAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerEvent(uint256,address)",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerEvent(uint256,address,uint64,uint64)",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setAttendanceProofAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAvaxUsdPriceFeed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setEventTimeRange",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxPriceAge",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setStableToken",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "settleEvent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ticketInfoOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ticketTypes",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REFUND_LOCK_BEFORE_START",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptedStableTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "attendanceProofAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "avaxUsdPriceFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyTicket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "buyTicketWithERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyTicketWithNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "configureTicketType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eventCanceled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "eventEndAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "eventExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eventNativeBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eventOrganizer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eventSettled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eventStartAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eventTicketBalanceOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eventTokenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStableTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasBought", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasValidTicket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxPriceAge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quoteNativePriceWei",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundCanceledTicket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundCanceledTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundCutoffAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerEvent(uint256,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerEvent(uint256,address,uint64,uint64)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAttendanceProofAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAvaxUsdPriceFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEventTimeRange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxPriceAge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStableToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ticketInfoOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ticketTypes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AttendanceProofUpdatedEvent {
  export type InputTuple = [attendanceProof: AddressLike];
  export type OutputTuple = [attendanceProof: string];
  export interface OutputObject {
    attendanceProof: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AvaxUsdPriceFeedUpdatedEvent {
  export type InputTuple = [feed: AddressLike];
  export type OutputTuple = [feed: string];
  export interface OutputObject {
    feed: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EventCanceledEvent {
  export type InputTuple = [eventId: BigNumberish, operator: AddressLike];
  export type OutputTuple = [eventId: bigint, operator: string];
  export interface OutputObject {
    eventId: bigint;
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EventRegisteredEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    organizer: AddressLike,
    startAt: BigNumberish,
    endAt: BigNumberish
  ];
  export type OutputTuple = [
    eventId: bigint,
    organizer: string,
    startAt: bigint,
    endAt: bigint
  ];
  export interface OutputObject {
    eventId: bigint;
    organizer: string;
    startAt: bigint;
    endAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EventSettledEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    organizer: AddressLike,
    nativeGross: BigNumberish,
    nativePlatformFee: BigNumberish,
    nativeOrganizerAmount: BigNumberish
  ];
  export type OutputTuple = [
    eventId: bigint,
    organizer: string,
    nativeGross: bigint,
    nativePlatformFee: bigint,
    nativeOrganizerAmount: bigint
  ];
  export interface OutputObject {
    eventId: bigint;
    organizer: string;
    nativeGross: bigint;
    nativePlatformFee: bigint;
    nativeOrganizerAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EventTimeRangeUpdatedEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    startAt: BigNumberish,
    endAt: BigNumberish
  ];
  export type OutputTuple = [eventId: bigint, startAt: bigint, endAt: bigint];
  export interface OutputObject {
    eventId: bigint;
    startAt: bigint;
    endAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EventTokenSettledEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    organizer: AddressLike,
    token: AddressLike,
    gross: BigNumberish,
    platformFee: BigNumberish,
    organizerAmount: BigNumberish
  ];
  export type OutputTuple = [
    eventId: bigint,
    organizer: string,
    token: string,
    gross: bigint,
    platformFee: bigint,
    organizerAmount: bigint
  ];
  export interface OutputObject {
    eventId: bigint;
    organizer: string;
    token: string;
    gross: bigint;
    platformFee: bigint;
    organizerAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxPriceAgeUpdatedEvent {
  export type InputTuple = [maxPriceAge: BigNumberish];
  export type OutputTuple = [maxPriceAge: bigint];
  export interface OutputObject {
    maxPriceAge: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformTreasuryUpdatedEvent {
  export type InputTuple = [treasury: AddressLike];
  export type OutputTuple = [treasury: string];
  export interface OutputObject {
    treasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StableTokenUpdatedEvent {
  export type InputTuple = [token: AddressLike, enabled: boolean];
  export type OutputTuple = [token: string, enabled: boolean];
  export interface OutputObject {
    token: string;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TicketMintedEvent {
  export type InputTuple = [
    user: AddressLike,
    eventId: BigNumberish,
    ticketTypeId: BigNumberish,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    eventId: bigint,
    ticketTypeId: bigint,
    tokenId: bigint
  ];
  export interface OutputObject {
    user: string;
    eventId: bigint;
    ticketTypeId: bigint;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TicketPaidEvent {
  export type InputTuple = [
    user: AddressLike,
    eventId: BigNumberish,
    ticketTypeId: BigNumberish,
    paymentToken: AddressLike,
    paymentAmount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    eventId: bigint,
    ticketTypeId: bigint,
    paymentToken: string,
    paymentAmount: bigint
  ];
  export interface OutputObject {
    user: string;
    eventId: bigint;
    ticketTypeId: bigint;
    paymentToken: string;
    paymentAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TicketRefundedEvent {
  export type InputTuple = [
    user: AddressLike,
    eventId: BigNumberish,
    ticketTypeId: BigNumberish,
    tokenId: BigNumberish,
    paymentToken: AddressLike,
    paymentAmount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    eventId: bigint,
    ticketTypeId: bigint,
    tokenId: bigint,
    paymentToken: string,
    paymentAmount: bigint
  ];
  export interface OutputObject {
    user: string;
    eventId: bigint;
    ticketTypeId: bigint;
    tokenId: bigint;
    paymentToken: string;
    paymentAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TicketTypeConfiguredEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    ticketTypeId: BigNumberish,
    priceUsd6: BigNumberish,
    maxSupply: BigNumberish,
    saleStart: BigNumberish,
    saleEnd: BigNumberish,
    transferable: boolean
  ];
  export type OutputTuple = [
    eventId: bigint,
    ticketTypeId: bigint,
    priceUsd6: bigint,
    maxSupply: bigint,
    saleStart: bigint,
    saleEnd: bigint,
    transferable: boolean
  ];
  export interface OutputObject {
    eventId: bigint;
    ticketTypeId: bigint;
    priceUsd6: bigint;
    maxSupply: bigint;
    saleStart: bigint;
    saleEnd: bigint;
    transferable: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TicketPass extends BaseContract {
  connect(runner?: ContractRunner | null): TicketPass;
  waitForDeployment(): Promise<this>;

  interface: TicketPassInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  REFUND_LOCK_BEFORE_START: TypedContractMethod<[], [bigint], "view">;

  acceptedStableTokens: TypedContractMethod<
    [token: AddressLike],
    [boolean],
    "view"
  >;

  approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  attendanceProofAddress: TypedContractMethod<[], [string], "view">;

  avaxUsdPriceFeed: TypedContractMethod<[], [string], "view">;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  buyTicket: TypedContractMethod<
    [eventId: BigNumberish, ticketTypeId: BigNumberish],
    [bigint],
    "payable"
  >;

  buyTicketWithERC20: TypedContractMethod<
    [
      eventId: BigNumberish,
      ticketTypeId: BigNumberish,
      paymentToken: AddressLike,
      maxPaymentAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  buyTicketWithNative: TypedContractMethod<
    [
      eventId: BigNumberish,
      ticketTypeId: BigNumberish,
      maxPaymentWei: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  cancelEvent: TypedContractMethod<
    [eventId: BigNumberish],
    [void],
    "nonpayable"
  >;

  configureTicketType: TypedContractMethod<
    [
      eventId: BigNumberish,
      ticketTypeId: BigNumberish,
      priceUsd6: BigNumberish,
      maxSupply: BigNumberish,
      saleStart: BigNumberish,
      saleEnd: BigNumberish,
      transferable: boolean
    ],
    [void],
    "nonpayable"
  >;

  eventCanceled: TypedContractMethod<
    [eventId: BigNumberish],
    [boolean],
    "view"
  >;

  eventEndAt: TypedContractMethod<[eventId: BigNumberish], [bigint], "view">;

  eventExists: TypedContractMethod<[eventId: BigNumberish], [boolean], "view">;

  eventNativeBalance: TypedContractMethod<
    [eventId: BigNumberish],
    [bigint],
    "view"
  >;

  eventOrganizer: TypedContractMethod<
    [eventId: BigNumberish],
    [string],
    "view"
  >;

  eventSettled: TypedContractMethod<[eventId: BigNumberish], [boolean], "view">;

  eventStartAt: TypedContractMethod<[eventId: BigNumberish], [bigint], "view">;

  eventTicketBalanceOf: TypedContractMethod<
    [eventId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;

  eventTokenBalance: TypedContractMethod<
    [eventId: BigNumberish, token: AddressLike],
    [bigint],
    "view"
  >;

  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getStableTokens: TypedContractMethod<[], [string[]], "view">;

  hasBought: TypedContractMethod<
    [eventId: BigNumberish, ticketTypeId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;

  hasValidTicket: TypedContractMethod<
    [eventId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;

  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  maxPriceAge: TypedContractMethod<[], [bigint], "view">;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  platformTreasury: TypedContractMethod<[], [string], "view">;

  quoteNativePriceWei: TypedContractMethod<
    [eventId: BigNumberish, ticketTypeId: BigNumberish],
    [bigint],
    "view"
  >;

  refundCanceledTicket: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  refundCanceledTickets: TypedContractMethod<
    [tokenIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  refundCutoffAt: TypedContractMethod<
    [eventId: BigNumberish],
    [bigint],
    "view"
  >;

  "registerEvent(uint256,address)": TypedContractMethod<
    [eventId: BigNumberish, organizer: AddressLike],
    [void],
    "nonpayable"
  >;

  "registerEvent(uint256,address,uint64,uint64)": TypedContractMethod<
    [
      eventId: BigNumberish,
      organizer: AddressLike,
      startAt: BigNumberish,
      endAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestRefund: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setAttendanceProofAddress: TypedContractMethod<
    [attendanceProof: AddressLike],
    [void],
    "nonpayable"
  >;

  setAvaxUsdPriceFeed: TypedContractMethod<
    [feed: AddressLike],
    [void],
    "nonpayable"
  >;

  setEventTimeRange: TypedContractMethod<
    [eventId: BigNumberish, startAt: BigNumberish, endAt: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMaxPriceAge: TypedContractMethod<
    [nextMaxPriceAge: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPlatformTreasury: TypedContractMethod<
    [treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  setStableToken: TypedContractMethod<
    [token: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;

  settleEvent: TypedContractMethod<
    [eventId: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  ticketInfoOf: TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [bigint, bigint, string, string, bigint, boolean, boolean] & {
        eventId: bigint;
        ticketTypeId: bigint;
        buyer: string;
        paymentToken: string;
        paymentAmount: bigint;
        transferred: boolean;
        refunded: boolean;
      }
    ],
    "view"
  >;

  ticketTypes: TypedContractMethod<
    [eventId: BigNumberish, ticketTypeId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, boolean] & {
        priceUsd6: bigint;
        maxSupply: bigint;
        sold: bigint;
        saleStart: bigint;
        saleEnd: bigint;
        transferable: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REFUND_LOCK_BEFORE_START"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptedStableTokens"
  ): TypedContractMethod<[token: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "attendanceProofAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "avaxUsdPriceFeed"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "buyTicket"
  ): TypedContractMethod<
    [eventId: BigNumberish, ticketTypeId: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "buyTicketWithERC20"
  ): TypedContractMethod<
    [
      eventId: BigNumberish,
      ticketTypeId: BigNumberish,
      paymentToken: AddressLike,
      maxPaymentAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "buyTicketWithNative"
  ): TypedContractMethod<
    [
      eventId: BigNumberish,
      ticketTypeId: BigNumberish,
      maxPaymentWei: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "cancelEvent"
  ): TypedContractMethod<[eventId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "configureTicketType"
  ): TypedContractMethod<
    [
      eventId: BigNumberish,
      ticketTypeId: BigNumberish,
      priceUsd6: BigNumberish,
      maxSupply: BigNumberish,
      saleStart: BigNumberish,
      saleEnd: BigNumberish,
      transferable: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eventCanceled"
  ): TypedContractMethod<[eventId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "eventEndAt"
  ): TypedContractMethod<[eventId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "eventExists"
  ): TypedContractMethod<[eventId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "eventNativeBalance"
  ): TypedContractMethod<[eventId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "eventOrganizer"
  ): TypedContractMethod<[eventId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "eventSettled"
  ): TypedContractMethod<[eventId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "eventStartAt"
  ): TypedContractMethod<[eventId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "eventTicketBalanceOf"
  ): TypedContractMethod<
    [eventId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "eventTokenBalance"
  ): TypedContractMethod<
    [eventId: BigNumberish, token: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getStableTokens"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "hasBought"
  ): TypedContractMethod<
    [eventId: BigNumberish, ticketTypeId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasValidTicket"
  ): TypedContractMethod<
    [eventId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxPriceAge"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "platformTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "quoteNativePriceWei"
  ): TypedContractMethod<
    [eventId: BigNumberish, ticketTypeId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "refundCanceledTicket"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "refundCanceledTickets"
  ): TypedContractMethod<[tokenIds: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "refundCutoffAt"
  ): TypedContractMethod<[eventId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerEvent(uint256,address)"
  ): TypedContractMethod<
    [eventId: BigNumberish, organizer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerEvent(uint256,address,uint64,uint64)"
  ): TypedContractMethod<
    [
      eventId: BigNumberish,
      organizer: AddressLike,
      startAt: BigNumberish,
      endAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestRefund"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAttendanceProofAddress"
  ): TypedContractMethod<[attendanceProof: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAvaxUsdPriceFeed"
  ): TypedContractMethod<[feed: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEventTimeRange"
  ): TypedContractMethod<
    [eventId: BigNumberish, startAt: BigNumberish, endAt: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMaxPriceAge"
  ): TypedContractMethod<[nextMaxPriceAge: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformTreasury"
  ): TypedContractMethod<[treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setStableToken"
  ): TypedContractMethod<
    [token: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settleEvent"
  ): TypedContractMethod<[eventId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ticketInfoOf"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [bigint, bigint, string, string, bigint, boolean, boolean] & {
        eventId: bigint;
        ticketTypeId: bigint;
        buyer: string;
        paymentToken: string;
        paymentAmount: bigint;
        transferred: boolean;
        refunded: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "ticketTypes"
  ): TypedContractMethod<
    [eventId: BigNumberish, ticketTypeId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, boolean] & {
        priceUsd6: bigint;
        maxSupply: bigint;
        sold: bigint;
        saleStart: bigint;
        saleEnd: bigint;
        transferable: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "AttendanceProofUpdated"
  ): TypedContractEvent<
    AttendanceProofUpdatedEvent.InputTuple,
    AttendanceProofUpdatedEvent.OutputTuple,
    AttendanceProofUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AvaxUsdPriceFeedUpdated"
  ): TypedContractEvent<
    AvaxUsdPriceFeedUpdatedEvent.InputTuple,
    AvaxUsdPriceFeedUpdatedEvent.OutputTuple,
    AvaxUsdPriceFeedUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EventCanceled"
  ): TypedContractEvent<
    EventCanceledEvent.InputTuple,
    EventCanceledEvent.OutputTuple,
    EventCanceledEvent.OutputObject
  >;
  getEvent(
    key: "EventRegistered"
  ): TypedContractEvent<
    EventRegisteredEvent.InputTuple,
    EventRegisteredEvent.OutputTuple,
    EventRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "EventSettled"
  ): TypedContractEvent<
    EventSettledEvent.InputTuple,
    EventSettledEvent.OutputTuple,
    EventSettledEvent.OutputObject
  >;
  getEvent(
    key: "EventTimeRangeUpdated"
  ): TypedContractEvent<
    EventTimeRangeUpdatedEvent.InputTuple,
    EventTimeRangeUpdatedEvent.OutputTuple,
    EventTimeRangeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EventTokenSettled"
  ): TypedContractEvent<
    EventTokenSettledEvent.InputTuple,
    EventTokenSettledEvent.OutputTuple,
    EventTokenSettledEvent.OutputObject
  >;
  getEvent(
    key: "MaxPriceAgeUpdated"
  ): TypedContractEvent<
    MaxPriceAgeUpdatedEvent.InputTuple,
    MaxPriceAgeUpdatedEvent.OutputTuple,
    MaxPriceAgeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PlatformTreasuryUpdated"
  ): TypedContractEvent<
    PlatformTreasuryUpdatedEvent.InputTuple,
    PlatformTreasuryUpdatedEvent.OutputTuple,
    PlatformTreasuryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "StableTokenUpdated"
  ): TypedContractEvent<
    StableTokenUpdatedEvent.InputTuple,
    StableTokenUpdatedEvent.OutputTuple,
    StableTokenUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TicketMinted"
  ): TypedContractEvent<
    TicketMintedEvent.InputTuple,
    TicketMintedEvent.OutputTuple,
    TicketMintedEvent.OutputObject
  >;
  getEvent(
    key: "TicketPaid"
  ): TypedContractEvent<
    TicketPaidEvent.InputTuple,
    TicketPaidEvent.OutputTuple,
    TicketPaidEvent.OutputObject
  >;
  getEvent(
    key: "TicketRefunded"
  ): TypedContractEvent<
    TicketRefundedEvent.InputTuple,
    TicketRefundedEvent.OutputTuple,
    TicketRefundedEvent.OutputObject
  >;
  getEvent(
    key: "TicketTypeConfigured"
  ): TypedContractEvent<
    TicketTypeConfiguredEvent.InputTuple,
    TicketTypeConfiguredEvent.OutputTuple,
    TicketTypeConfiguredEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "AttendanceProofUpdated(address)": TypedContractEvent<
      AttendanceProofUpdatedEvent.InputTuple,
      AttendanceProofUpdatedEvent.OutputTuple,
      AttendanceProofUpdatedEvent.OutputObject
    >;
    AttendanceProofUpdated: TypedContractEvent<
      AttendanceProofUpdatedEvent.InputTuple,
      AttendanceProofUpdatedEvent.OutputTuple,
      AttendanceProofUpdatedEvent.OutputObject
    >;

    "AvaxUsdPriceFeedUpdated(address)": TypedContractEvent<
      AvaxUsdPriceFeedUpdatedEvent.InputTuple,
      AvaxUsdPriceFeedUpdatedEvent.OutputTuple,
      AvaxUsdPriceFeedUpdatedEvent.OutputObject
    >;
    AvaxUsdPriceFeedUpdated: TypedContractEvent<
      AvaxUsdPriceFeedUpdatedEvent.InputTuple,
      AvaxUsdPriceFeedUpdatedEvent.OutputTuple,
      AvaxUsdPriceFeedUpdatedEvent.OutputObject
    >;

    "EventCanceled(uint256,address)": TypedContractEvent<
      EventCanceledEvent.InputTuple,
      EventCanceledEvent.OutputTuple,
      EventCanceledEvent.OutputObject
    >;
    EventCanceled: TypedContractEvent<
      EventCanceledEvent.InputTuple,
      EventCanceledEvent.OutputTuple,
      EventCanceledEvent.OutputObject
    >;

    "EventRegistered(uint256,address,uint64,uint64)": TypedContractEvent<
      EventRegisteredEvent.InputTuple,
      EventRegisteredEvent.OutputTuple,
      EventRegisteredEvent.OutputObject
    >;
    EventRegistered: TypedContractEvent<
      EventRegisteredEvent.InputTuple,
      EventRegisteredEvent.OutputTuple,
      EventRegisteredEvent.OutputObject
    >;

    "EventSettled(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      EventSettledEvent.InputTuple,
      EventSettledEvent.OutputTuple,
      EventSettledEvent.OutputObject
    >;
    EventSettled: TypedContractEvent<
      EventSettledEvent.InputTuple,
      EventSettledEvent.OutputTuple,
      EventSettledEvent.OutputObject
    >;

    "EventTimeRangeUpdated(uint256,uint64,uint64)": TypedContractEvent<
      EventTimeRangeUpdatedEvent.InputTuple,
      EventTimeRangeUpdatedEvent.OutputTuple,
      EventTimeRangeUpdatedEvent.OutputObject
    >;
    EventTimeRangeUpdated: TypedContractEvent<
      EventTimeRangeUpdatedEvent.InputTuple,
      EventTimeRangeUpdatedEvent.OutputTuple,
      EventTimeRangeUpdatedEvent.OutputObject
    >;

    "EventTokenSettled(uint256,address,address,uint256,uint256,uint256)": TypedContractEvent<
      EventTokenSettledEvent.InputTuple,
      EventTokenSettledEvent.OutputTuple,
      EventTokenSettledEvent.OutputObject
    >;
    EventTokenSettled: TypedContractEvent<
      EventTokenSettledEvent.InputTuple,
      EventTokenSettledEvent.OutputTuple,
      EventTokenSettledEvent.OutputObject
    >;

    "MaxPriceAgeUpdated(uint256)": TypedContractEvent<
      MaxPriceAgeUpdatedEvent.InputTuple,
      MaxPriceAgeUpdatedEvent.OutputTuple,
      MaxPriceAgeUpdatedEvent.OutputObject
    >;
    MaxPriceAgeUpdated: TypedContractEvent<
      MaxPriceAgeUpdatedEvent.InputTuple,
      MaxPriceAgeUpdatedEvent.OutputTuple,
      MaxPriceAgeUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PlatformTreasuryUpdated(address)": TypedContractEvent<
      PlatformTreasuryUpdatedEvent.InputTuple,
      PlatformTreasuryUpdatedEvent.OutputTuple,
      PlatformTreasuryUpdatedEvent.OutputObject
    >;
    PlatformTreasuryUpdated: TypedContractEvent<
      PlatformTreasuryUpdatedEvent.InputTuple,
      PlatformTreasuryUpdatedEvent.OutputTuple,
      PlatformTreasuryUpdatedEvent.OutputObject
    >;

    "StableTokenUpdated(address,bool)": TypedContractEvent<
      StableTokenUpdatedEvent.InputTuple,
      StableTokenUpdatedEvent.OutputTuple,
      StableTokenUpdatedEvent.OutputObject
    >;
    StableTokenUpdated: TypedContractEvent<
      StableTokenUpdatedEvent.InputTuple,
      StableTokenUpdatedEvent.OutputTuple,
      StableTokenUpdatedEvent.OutputObject
    >;

    "TicketMinted(address,uint256,uint256,uint256)": TypedContractEvent<
      TicketMintedEvent.InputTuple,
      TicketMintedEvent.OutputTuple,
      TicketMintedEvent.OutputObject
    >;
    TicketMinted: TypedContractEvent<
      TicketMintedEvent.InputTuple,
      TicketMintedEvent.OutputTuple,
      TicketMintedEvent.OutputObject
    >;

    "TicketPaid(address,uint256,uint256,address,uint256)": TypedContractEvent<
      TicketPaidEvent.InputTuple,
      TicketPaidEvent.OutputTuple,
      TicketPaidEvent.OutputObject
    >;
    TicketPaid: TypedContractEvent<
      TicketPaidEvent.InputTuple,
      TicketPaidEvent.OutputTuple,
      TicketPaidEvent.OutputObject
    >;

    "TicketRefunded(address,uint256,uint256,uint256,address,uint256)": TypedContractEvent<
      TicketRefundedEvent.InputTuple,
      TicketRefundedEvent.OutputTuple,
      TicketRefundedEvent.OutputObject
    >;
    TicketRefunded: TypedContractEvent<
      TicketRefundedEvent.InputTuple,
      TicketRefundedEvent.OutputTuple,
      TicketRefundedEvent.OutputObject
    >;

    "TicketTypeConfigured(uint256,uint256,uint256,uint256,uint64,uint64,bool)": TypedContractEvent<
      TicketTypeConfiguredEvent.InputTuple,
      TicketTypeConfiguredEvent.OutputTuple,
      TicketTypeConfiguredEvent.OutputObject
    >;
    TicketTypeConfigured: TypedContractEvent<
      TicketTypeConfiguredEvent.InputTuple,
      TicketTypeConfiguredEvent.OutputTuple,
      TicketTypeConfiguredEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
