/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAttendanceProof__factory } from "./IAttendanceProof__factory";
export { ReviewAnchor__factory } from "./ReviewAnchor__factory";
