/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAttendanceProof } from "./IAttendanceProof";
export type { ReviewAnchor } from "./ReviewAnchor";
