/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ReviewAnchorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attendanceProof"
      | "eventRatingCount"
      | "eventTotalScore"
      | "getEventRatingSummary"
      | "hasRated"
      | "isMinter"
      | "owner"
      | "ratingInfoOf"
      | "renounceOwnership"
      | "setAttendanceProof"
      | "setMinter"
      | "submitRating"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AttendanceProofUpdated"
      | "OwnershipTransferred"
      | "RatingSubmitted"
      | "ReviewMinterUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "attendanceProof",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "eventRatingCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "eventTotalScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEventRatingSummary",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRated",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMinter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ratingInfoOf",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAttendanceProof",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinter",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "submitRating",
    values: [BigNumberish, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "attendanceProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eventRatingCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eventTotalScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEventRatingSummary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRated", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isMinter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ratingInfoOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAttendanceProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setMinter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitRating",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AttendanceProofUpdatedEvent {
  export type InputTuple = [attendanceProof: AddressLike];
  export type OutputTuple = [attendanceProof: string];
  export interface OutputObject {
    attendanceProof: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RatingSubmittedEvent {
  export type InputTuple = [
    user: AddressLike,
    eventId: BigNumberish,
    rating: BigNumberish,
    reviewHash: BytesLike
  ];
  export type OutputTuple = [
    user: string,
    eventId: bigint,
    rating: bigint,
    reviewHash: string
  ];
  export interface OutputObject {
    user: string;
    eventId: bigint;
    rating: bigint;
    reviewHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReviewMinterUpdatedEvent {
  export type InputTuple = [minter: AddressLike, allowed: boolean];
  export type OutputTuple = [minter: string, allowed: boolean];
  export interface OutputObject {
    minter: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReviewAnchor extends BaseContract {
  connect(runner?: ContractRunner | null): ReviewAnchor;
  waitForDeployment(): Promise<this>;

  interface: ReviewAnchorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attendanceProof: TypedContractMethod<[], [string], "view">;

  eventRatingCount: TypedContractMethod<
    [eventId: BigNumberish],
    [bigint],
    "view"
  >;

  eventTotalScore: TypedContractMethod<
    [eventId: BigNumberish],
    [bigint],
    "view"
  >;

  getEventRatingSummary: TypedContractMethod<
    [eventId: BigNumberish],
    [[bigint, bigint] & { totalScore: bigint; count: bigint }],
    "view"
  >;

  hasRated: TypedContractMethod<
    [eventId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;

  isMinter: TypedContractMethod<[minter: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ratingInfoOf: TypedContractMethod<
    [eventId: BigNumberish, user: AddressLike],
    [
      [bigint, string, bigint] & {
        rating: bigint;
        reviewHash: string;
        submittedAt: bigint;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAttendanceProof: TypedContractMethod<
    [attendanceProofAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setMinter: TypedContractMethod<
    [minter: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  submitRating: TypedContractMethod<
    [
      eventId: BigNumberish,
      user: AddressLike,
      rating: BigNumberish,
      reviewHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attendanceProof"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "eventRatingCount"
  ): TypedContractMethod<[eventId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "eventTotalScore"
  ): TypedContractMethod<[eventId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEventRatingSummary"
  ): TypedContractMethod<
    [eventId: BigNumberish],
    [[bigint, bigint] & { totalScore: bigint; count: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasRated"
  ): TypedContractMethod<
    [eventId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isMinter"
  ): TypedContractMethod<[minter: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ratingInfoOf"
  ): TypedContractMethod<
    [eventId: BigNumberish, user: AddressLike],
    [
      [bigint, string, bigint] & {
        rating: bigint;
        reviewHash: string;
        submittedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAttendanceProof"
  ): TypedContractMethod<
    [attendanceProofAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMinter"
  ): TypedContractMethod<
    [minter: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitRating"
  ): TypedContractMethod<
    [
      eventId: BigNumberish,
      user: AddressLike,
      rating: BigNumberish,
      reviewHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AttendanceProofUpdated"
  ): TypedContractEvent<
    AttendanceProofUpdatedEvent.InputTuple,
    AttendanceProofUpdatedEvent.OutputTuple,
    AttendanceProofUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RatingSubmitted"
  ): TypedContractEvent<
    RatingSubmittedEvent.InputTuple,
    RatingSubmittedEvent.OutputTuple,
    RatingSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ReviewMinterUpdated"
  ): TypedContractEvent<
    ReviewMinterUpdatedEvent.InputTuple,
    ReviewMinterUpdatedEvent.OutputTuple,
    ReviewMinterUpdatedEvent.OutputObject
  >;

  filters: {
    "AttendanceProofUpdated(address)": TypedContractEvent<
      AttendanceProofUpdatedEvent.InputTuple,
      AttendanceProofUpdatedEvent.OutputTuple,
      AttendanceProofUpdatedEvent.OutputObject
    >;
    AttendanceProofUpdated: TypedContractEvent<
      AttendanceProofUpdatedEvent.InputTuple,
      AttendanceProofUpdatedEvent.OutputTuple,
      AttendanceProofUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RatingSubmitted(address,uint256,uint8,bytes32)": TypedContractEvent<
      RatingSubmittedEvent.InputTuple,
      RatingSubmittedEvent.OutputTuple,
      RatingSubmittedEvent.OutputObject
    >;
    RatingSubmitted: TypedContractEvent<
      RatingSubmittedEvent.InputTuple,
      RatingSubmittedEvent.OutputTuple,
      RatingSubmittedEvent.OutputObject
    >;

    "ReviewMinterUpdated(address,bool)": TypedContractEvent<
      ReviewMinterUpdatedEvent.InputTuple,
      ReviewMinterUpdatedEvent.OutputTuple,
      ReviewMinterUpdatedEvent.OutputObject
    >;
    ReviewMinterUpdated: TypedContractEvent<
      ReviewMinterUpdatedEvent.InputTuple,
      ReviewMinterUpdatedEvent.OutputTuple,
      ReviewMinterUpdatedEvent.OutputObject
    >;
  };
}
