/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAttendanceProof,
  IAttendanceProofInterface,
} from "../../../contracts/TicketPass.sol/IAttendanceProof";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "eventId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "hasAttendanceProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAttendanceProof__factory {
  static readonly abi = _abi;
  static createInterface(): IAttendanceProofInterface {
    return new Interface(_abi) as IAttendanceProofInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAttendanceProof {
    return new Contract(address, _abi, runner) as unknown as IAttendanceProof;
  }
}
